# -*- coding: utf-8 -*-
"""mini projectipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/184R_wBMGZkogrgjtJIsfud5H-CENy0re
"""

uploaded = files.upload()   # Now upload deliveries.csv

from google.colab import files
uploaded = files.upload()

import pandas as pd

matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

print(deliveries.columns)

import matplotlib.pyplot as plt

# Group runs by batter and sort
top_batsmen = deliveries.groupby("batter")["batsman_runs"].sum().sort_values(ascending=False).head(10)

# Plot bar chart
plt.figure(figsize=(10,6))
top_batsmen.plot(kind="bar", color="orange")
plt.title("Top 10 Batsmen by Runs in IPL", fontsize=16)
plt.xlabel("Batsman")
plt.ylabel("Total Runs")
plt.xticks(rotation=45)
plt.show()

# Count how many times each player won 'Player of the Match'
top_players = matches["player_of_match"].value_counts().head(10)

# Plot bar chart
plt.figure(figsize=(10,6))
top_players.plot(kind="bar", color="green")
plt.title("Top 10 Players by Man of the Match Awards", fontsize=16)
plt.xlabel("Player")
plt.ylabel("Number of Awards")
plt.xticks(rotation=45)
plt.show()

wins = matches["winner"].value_counts()

plt.figure(figsize=(8,8))
wins.plot(kind="pie", autopct="%1.1f%%", startangle=140, colormap="tab20")
plt.title("Matches Won by Each Team")
plt.ylabel("")
plt.show()

venues = matches["venue"].value_counts().head(10)

plt.figure(figsize=(10,6))
venues.plot(kind="bar", color="green")
plt.title("Top Venues by Match Count")
plt.xlabel("Venue")
plt.ylabel("Number of Matches")
plt.xticks(rotation=75)
plt.show()